name: Update Quote

on:
  schedule:
  - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: update
        run: |
          bash scripts/update.sh

      - name: push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.html
          git commit -m "update quote"
          git push
